Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20111129-3
extra : transplant_source : %C7%8Bd%5B1l%A8%C5%DF%0B%8CZ%01%F4%F5%B4B%F0%5E%AA