Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20111202-4
extra : transplant_source : %B1%AD%CD%D9w%A1J27%A0%8E%B0%86%B9x%98Z%60%D0%BE